version: 2
registries:
  # The registry is technically public, but GitHub
  # still requires authentication to access it.
  # https://github.com/orgs/community/discussions/23386#discussioncomment-3240193
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.ACTION_PAT }}
updates:
  - package-ecosystem: "npm"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
    registries: "*"
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
