version: 2
updates:
  - package-ecosystem: "npm"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
